# 指定基础镜像
FROM openjdk:17-oracle
LABEL maintainer="2471835953@qq.com"
# 挂载目录
VOLUME /home/twelvet
# 创建目录
RUN mkdir -p /home/twelvet
# 指定路径
WORKDIR /home/twelvet
# 复制jar文件到路径
COPY ./jar/twelvet-admin.jar /home/twelvet/twelvet-admin.jar
# 启动网关服务
ENV TZ=America/New_York JAVA_OPTS="-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
CMD sleep 60; java -jar twelvet-admin.jar
